<?php

namespace axenox\AtlassianConnector\AI\Tools;

use axenox\AtlassianConnector\Common\MarkdownToAdfConverter;
use axenox\GenAI\Common\AbstractAiTool;
use axenox\GenAI\Common\AiToolResultString;
use axenox\GenAI\Exceptions\AiToolRuntimeError;
use axenox\GenAI\Interfaces\AiAgentInterface;
use axenox\GenAI\Interfaces\AiPromptInterface;
use axenox\GenAI\Interfaces\AiToolResultInterface;
use exface\Core\CommonLogic\Actions\ServiceParameter;
use exface\Core\CommonLogic\UxonObject;
use exface\Core\DataTypes\ComparatorDataType;
use exface\Core\DataTypes\JsonDataType;
use exface\Core\DataTypes\StringDataType;
use exface\Core\Exceptions\InvalidArgumentException;
use exface\Core\Exceptions\RuntimeException as CoreRuntimeException;
use exface\Core\Factories\DataConnectionFactory;
use exface\Core\Factories\DataSheetFactory;
use exface\Core\Factories\DataTypeFactory;
use exface\Core\Interfaces\DataTypes\DataTypeInterface;
use exface\Core\Interfaces\WorkbenchInterface;
use exface\UrlDataConnector\Interfaces\HttpConnectionInterface;
use GuzzleHttp\Psr7\Request;

/**
 * Replaces one configured section in a Jira ticket description without changing other sections.
 *
 * The tool reads the current raw ADF description through the fixed Jira issue metaobject immediately
 * before updating it. It replaces the content after the configured top-level heading up to the next
 * heading of the same or a higher level. If the heading does not exist, it appends the new section.
 * Duplicate matching headings and malformed descriptions are rejected without writing anything.
 *
 * The model only supplies a ticket key and Markdown content. The section heading is fixed in the
 * tool configuration. Supported Markdown is converted to ADF and unsupported syntax remains plain text.
 *
 * ## Example
 *
 * ```
 * {
 *     "UpdateAgentAnalysis": {
 *         "alias": "axenox.AtlassianConnector.UpdateJiraDescriptionSectionTool",
 *         "description": "Replaces the managed Agent Analysis section in a Jira ticket.",
 *         "connection_alias": "your.App.JiraConnection",
 *         "section_heading": "Agent Analysis",
 *         "ai_generated_hint": "This plan was generated by AI and may contain errors. Verify it before implementation.",
 *         "allowed_key_prefixes": ["ABC-"]
 *     }
 * }
 *
 * ```
 */
class UpdateJiraDescriptionSectionTool extends AbstractAiTool
{
    public const ARG_KEY = 'key';

    public const ARG_CONTENT = 'content';

    private const JIRA_ISSUE_OBJECT = 'axenox.AtlassianConnector.JIRA_ISSUE';

    private const KEY_ATTRIBUTE = 'key';

    private const DESCRIPTION_ATTRIBUTE = 'description';

    private const DEFAULT_SECTION_HEADING_LEVEL = 2;

    private const DEFAULT_MAX_CONTENT_LENGTH = 20000;

    private const DEFAULT_AI_GENERATED_HINT = 'This content was generated by AI and may contain errors. Verify it before use.';

    private ?string $connectionAlias = null;

    private ?string $sectionHeading = null;

    private string $aiGeneratedHint = self::DEFAULT_AI_GENERATED_HINT;

    private int $maxContentLength = self::DEFAULT_MAX_CONTENT_LENGTH;

    /**
     * @var string[]
     */
    private array $allowedKeyPrefixes = [];

    /**
     * {@inheritDoc}
     * @see \axenox\GenAI\Interfaces\AiToolInterface::invoke()
     */
    public function invoke(AiAgentInterface $agent, AiPromptInterface $prompt, array $arguments): AiToolResultInterface
    {
        $key = trim((string) ($arguments[0] ?? ''));
        $content = trim((string) ($arguments[1] ?? ''));

        $this->validateInvocation($prompt, $key, $content);

        try {
            // Always base the update on the latest raw ADF instead of an earlier agent read.
            $description = $this->readDescription($key);
            $updatedDescription = $this->replaceSection($description, $content);
            $connection = $this->getConnection();
            $body = json_encode(
                ['fields' => [self::DESCRIPTION_ATTRIBUTE => $this->normalizeAdfForJson($updatedDescription)]],
                JSON_THROW_ON_ERROR
            );
            $response = $connection->sendRequest(new Request(
                'PUT',
                'issue/' . rawurlencode($key),
                ['Accept' => 'application/json', 'Content-Type' => 'application/json'],
                $body
            ));
        } catch (AiToolRuntimeError $e) {
            throw $e;
        } catch (\Throwable $e) {
            throw new AiToolRuntimeError(
                $this,
                $prompt,
                'Failed to update section "' . $this->sectionHeading . '" in Jira ticket "' . $key . '": ' . $e->getMessage(),
                null,
                $e
            );
        }

        if ($response === null) {
            throw new AiToolRuntimeError($this, $prompt, 'Jira returned no response while updating ticket "' . $key . '".');
        }
        if ($response->getStatusCode() >= 400) {
            throw new AiToolRuntimeError(
                $this,
                $prompt,
                'Jira rejected the update for "' . $key . '": HTTP ' . $response->getStatusCode()
                . ' - ' . substr((string) $response->getBody(), 0, 500)
            );
        }

        return new AiToolResultString(
            $this,
            $arguments,
            'Section "' . $this->sectionHeading . '" updated in Jira ticket "' . $key . '".',
            $this->getReturnDataType()
        );
    }

    /**
    * Validates required arguments, configured boundaries and the ticket allow-list.
    *
    * @param AiPromptInterface $prompt
    * @param string $key
    * @param string $content
    * @return void
    */
    private function validateInvocation(AiPromptInterface $prompt, string $key, string $content): void
    {
        if ($key === '') {
            throw new AiToolRuntimeError($this, $prompt, 'Missing required argument: key');
        }
        if ($content === '') {
            throw new AiToolRuntimeError($this, $prompt, 'Missing required argument: content');
        }
        if (strlen($content) > $this->maxContentLength) {
            throw new AiToolRuntimeError(
                $this,
                $prompt,
                'Content exceeds the configured maximum length of ' . $this->maxContentLength . ' bytes.'
            );
        }
        if ($this->connectionAlias === null) {
            throw new AiToolRuntimeError($this, $prompt, 'No Jira connection configured. Set `connection_alias` on the tool.');
        }
        if ($this->sectionHeading === null) {
            throw new AiToolRuntimeError($this, $prompt, 'No managed section configured. Set `section_heading` on the tool.');
        }
        if (! $this->isKeyAllowed($key)) {
            throw new AiToolRuntimeError($this, $prompt, 'Updating Jira ticket "' . $key . '" is not allowed by this tool\'s configuration.');
        }
    }

    /**
    * Reads the latest raw ADF description for exactly one Jira issue through its metaobject.
    *
    * @param string $key
    * @return array
    */
    private function readDescription(string $key): array
    {
        $sheet = DataSheetFactory::createFromObjectIdOrAlias($this->getWorkbench(), self::JIRA_ISSUE_OBJECT);
        $sheet->getColumns()->addMultiple([self::KEY_ATTRIBUTE, self::DESCRIPTION_ATTRIBUTE]);
        $sheet->getFilters()->addConditionFromString(self::KEY_ATTRIBUTE, $key, ComparatorDataType::EQUALS);
        $sheet->dataRead();

        if ($sheet->countRows() !== 1) {
            throw new CoreRuntimeException(
                'Expected exactly one Jira issue for key "' . $key . '", got ' . $sheet->countRows() . '.'
            );
        }

        $descriptionJson = $sheet->getCellValue(self::DESCRIPTION_ATTRIBUTE, 0);
        if ($descriptionJson === null || $descriptionJson === '') {
            return ['type' => 'doc', 'version' => 1, 'content' => []];
        }
        if (! is_string($descriptionJson)) {
            throw new CoreRuntimeException('The Jira description is not a JSON string.');
        }

        $description = JsonDataType::decodeJson($descriptionJson, true);
        if (
            ! is_array($description)
            || ($description['type'] ?? null) !== 'doc'
            || ! isset($description['content'])
            || ! is_array($description['content'])
        ) {
            throw new CoreRuntimeException('The Jira description is not a valid ADF document.');
        }
        return $description;
    }

    /**
    * Replaces the managed top-level ADF section or appends it when it does not exist.
    *
    * @param array $description
    * @param string $content
    * @return array
    */
    private function replaceSection(array $description, string $content): array
    {
        $nodes = $description['content'];
        $matches = [];
        // Sections are defined only by top-level headings; nested headings cannot capture surrounding content.
        foreach ($nodes as $index => $node) {
            if ($this->isManagedHeading($node)) {
                $matches[] = $index;
            }
        }

        if (count($matches) > 1) {
            throw new CoreRuntimeException(
                'The Jira description contains multiple headings named "' . $this->sectionHeading
                . '". No changes were made.'
            );
        }

        if ($matches === []) {
            $newSectionNodes = (new MarkdownToAdfConverter())->convert($content, self::DEFAULT_SECTION_HEADING_LEVEL);
            array_unshift($newSectionNodes, $this->buildAiGeneratedHintNode());
            $nodes[] = $this->buildHeadingNode();
            array_push($nodes, ...$newSectionNodes);
        } else {
            $headingIndex = $matches[0];
            $headingLevel = (int) ($nodes[$headingIndex]['attrs']['level'] ?? 0);
            if ($headingLevel < 1 || $headingLevel > 6) {
                throw new CoreRuntimeException('The managed section heading has an invalid ADF heading level.');
            }
            $newSectionNodes = (new MarkdownToAdfConverter())->convert($content, $headingLevel);
            array_unshift($newSectionNodes, $this->buildAiGeneratedHintNode());
            $sectionStart = $headingIndex + 1;
            $sectionEnd = count($nodes);
            // A heading at the same or a higher structural level starts the next section.
            for ($index = $sectionStart; $index < count($nodes); $index++) {
                $node = $nodes[$index];
                if (
                    ($node['type'] ?? null) === 'heading'
                    && (int) ($node['attrs']['level'] ?? 1) <= $headingLevel
                ) {
                    $sectionEnd = $index;
                    break;
                }
            }

            $prefix = array_slice($nodes, 0, $sectionStart);
            $suffix = array_slice($nodes, $sectionEnd);
            $nodes = array_merge($prefix, $newSectionNodes, $suffix);
            // Fail closed if the splice ever changes nodes outside the managed section.
            $preservedSuffix = $suffix === [] ? [] : array_slice($nodes, -count($suffix));
            if (array_slice($nodes, 0, count($prefix)) !== $prefix || $preservedSuffix !== $suffix) {
                throw new CoreRuntimeException('Internal safety check failed while preserving content outside the managed section.');
            }
        }

        $description['content'] = $nodes;
        return $description;
    }

    /**
     * Restores empty ADF attribute maps that associative JSON decoding turns into PHP arrays.
     *
     * @param mixed $value
     * @param string|null $key
     * @return mixed
     */
    private function normalizeAdfForJson($value, string $key = null)
    {
        if ($key === 'attrs' && $value === []) {
            return (object) [];
        }
        if (! is_array($value)) {
            return $value;
        }
        foreach ($value as $childKey => $childValue) {
            $value[$childKey] = $this->normalizeAdfForJson($childValue, is_string($childKey) ? $childKey : null);
        }
        return $value;
    }

    /**
    * Determines whether an ADF node is the configured section heading.
    *
    * @param mixed $node
    * @return bool
    */
    private function isManagedHeading($node): bool
    {
        return is_array($node)
            && ($node['type'] ?? null) === 'heading'
            && trim($this->getNodeText($node)) === $this->sectionHeading;
    }

    /**
    * Recursively extracts plain text from an ADF node for heading comparison.
    *
    * @param array $node
    * @return string
    */
    private function getNodeText(array $node): string
    {
        $text = (string) ($node['text'] ?? '');
        foreach ($node['content'] ?? [] as $child) {
            if (is_array($child)) {
                $text .= $this->getNodeText($child);
            }
        }
        return $text;
    }

    /**
    * Builds the ADF heading node used when the managed section is missing.
    *
    * @return array
    */
    private function buildHeadingNode(): array
    {
        return [
            'type' => 'heading',
            'attrs' => ['level' => self::DEFAULT_SECTION_HEADING_LEVEL],
            'content' => [['type' => 'text', 'text' => $this->sectionHeading]]
        ];
    }

    /**
     * Builds the warning panel that identifies the managed section as AI-generated content.
     *
     * @return array
     */
    private function buildAiGeneratedHintNode(): array
    {
        return [
            'type' => 'panel',
            'attrs' => ['panelType' => 'warning'],
            'content' => [[
                'type' => 'paragraph',
                'content' => [['type' => 'text', 'text' => $this->aiGeneratedHint]]
            ]]
        ];
    }

    /**
    * Loads the configured Jira connection and ensures that it supports HTTP requests.
    *
    * @return HttpConnectionInterface
    */
    private function getConnection(): HttpConnectionInterface
    {
        $connection = DataConnectionFactory::createFromModel($this->getWorkbench(), $this->connectionAlias);
        if (! $connection instanceof HttpConnectionInterface) {
            throw new CoreRuntimeException('The configured Jira connection must be an HTTP connection.');
        }
        return $connection;
    }

    /**
    * Checks the ticket key against the configured prefixes.
    *
    * @param string $key
    * @return bool
    */
    private function isKeyAllowed(string $key): bool
    {
        foreach ($this->allowedKeyPrefixes as $prefix) {
            if (StringDataType::startsWith($key, $prefix, false)) {
                return true;
            }
        }
        return false;
    }

    /**
     * The Jira HTTP connection used to update the issue.
     *
     * @uxon-property connection_alias
     * @uxon-type metamodel:connection
     * @uxon-required true
     *
     * @param string $value
     * @return UpdateJiraDescriptionSectionTool
     */
    public function setConnectionAlias(string $value): UpdateJiraDescriptionSectionTool
    {
        $this->connectionAlias = trim($value);
        return $this;
    }

    /**
     * Exact top-level heading whose content this tool manages.
     *
     * @uxon-property section_heading
     * @uxon-type string
     * @uxon-required true
     *
     * @param string $value
     * @return UpdateJiraDescriptionSectionTool
     */
    public function setSectionHeading(string $value): UpdateJiraDescriptionSectionTool
    {
        $value = trim($value);
        if ($value === '') {
            throw new InvalidArgumentException('`section_heading` must not be empty.');
        }
        $this->sectionHeading = $value;
        return $this;
    }

    /**
     * Warning shown at the beginning of every managed section to identify AI-generated content.
     *
     * The hint is rendered as a Jira warning panel and cannot be disabled. Configure a localized
     * or use-case-specific warning when the default text is not suitable.
     *
     * @uxon-property ai_generated_hint
     * @uxon-type string
     * @uxon-default This content was generated by AI and may contain errors. Verify it before use.
     * @uxon-translatable true
     *
     * @param string $value
     * @return UpdateJiraDescriptionSectionTool
     */
    public function setAiGeneratedHint(string $value): UpdateJiraDescriptionSectionTool
    {
        $value = trim($value);
        if ($value === '') {
            throw new InvalidArgumentException('`ai_generated_hint` must not be empty.');
        }
        $this->aiGeneratedHint = $value;
        return $this;
    }

    /**
     * Maximum number of chars accepted in the replacement content.
     *
     * @uxon-property max_content_length
     * @uxon-type integer
     * @uxon-default 20000
     *
     * @param int $value
     * @return UpdateJiraDescriptionSectionTool
     */
    public function setMaxContentLength(int $value): UpdateJiraDescriptionSectionTool
    {
        if ($value < 1) {
            throw new InvalidArgumentException('`max_content_length` must be greater than zero.');
        }
        $this->maxContentLength = $value;
        return $this;
    }

    /**
     * Only allow tickets whose key starts with one of these prefixes.
     *
     * @uxon-property allowed_key_prefixes
     * @uxon-type string[]
     * @uxon-template ["PROJECT-"]
     *
     * @param UxonObject $value
     * @return UpdateJiraDescriptionSectionTool
     */
    public function setAllowedKeyPrefixes(UxonObject $value): UpdateJiraDescriptionSectionTool
    {
        $prefixes = [];
        foreach ($value->toArray() as $prefix) {
            if (! is_string($prefix) || trim($prefix) === '') {
                throw new InvalidArgumentException('Every `allowed_key_prefixes` entry must be a non-empty string.');
            }
            $prefixes[] = trim($prefix);
        }
        $this->allowedKeyPrefixes = array_values(array_unique($prefixes));
        return $this;
    }

    /**
     * {@inheritDoc}
     * @see \axenox\GenAI\Interfaces\AiToolInterface::getRules()
     */
    public function getRules(): ?string
    {
        $rules = [
            '- This tool may only replace the configured Jira description section "' . ($this->sectionHeading ?? '') . '".',
            '- Supply Markdown content without the managed section heading; supported Markdown is converted to Jira ADF.',
            '- Do not add an AI disclaimer to the content; the tool inserts its configured warning automatically.',
            '- Never use this tool to edit any other part of a Jira ticket.'
        ];
        if ($this->allowedKeyPrefixes === []) {
            $rules[] = '- No Jira ticket keys are currently allowed. Do not call this tool.';
        }
        if ($this->allowedKeyPrefixes !== []) {
            $rules[] = '- Only update ticket keys starting with: "' . implode('", "', $this->allowedKeyPrefixes) . '".';
        }
        return implode("\n", $rules);
    }

    /**
     * {@inheritDoc}
     * @see \axenox\GenAI\Common\AbstractAiTool::getArgumentsTemplates()
     */
    protected static function getArgumentsTemplates(WorkbenchInterface $workbench): array
    {
        $self = new self($workbench);
        return [
            (new ServiceParameter($self))
                ->setName(self::ARG_KEY)
                ->setDescription('The Jira issue key, e.g. "ABC-123".')
                ->setRequired(true),
            (new ServiceParameter($self))
                ->setName(self::ARG_CONTENT)
                ->setDescription('Markdown to place in the managed section. Unsupported syntax remains plain text.')
                ->setRequired(true)
        ];
    }

    /**
     * {@inheritDoc}
     * @see \axenox\GenAI\Interfaces\AiToolInterface::getReturnDataType()
     */
    public function getReturnDataType(): DataTypeInterface
    {
        return DataTypeFactory::createFromPrototype($this->getWorkbench(), StringDataType::class);
    }
}